blank_issues_enabled: false
contact_links:
  - name: 💬 Kurayami Shadows Discord
    url: https://discord.gg/CdKqcMwErf
    about: Ask questions, get real-time help, and interact with other summoners and creators.
